'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class edituser

	'''<summary>
	'''subMenu control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents subMenu As Global.PATMAP.tabmenu

	'''<summary>
	'''lblTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''btnSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSave As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnCancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblFirstName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblFirstName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''uplFirstName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents uplFirstName As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''txtFirstName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHFirstName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHFirstName As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblLastName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblLastName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''uplLastName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents uplLastName As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''txtLastName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHLastName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHLastName As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblOrganization control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblOrganization As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtOrganization control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtOrganization As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHOrganization control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHOrganization As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblPosition control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblPosition As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtPosition control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtPosition As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHPosition control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHPosition As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblEmail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtEmail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHEmail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHEmail As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblWorkPhone control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblWorkPhone As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtWP1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtWP1 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtWP2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtWP2 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtWP3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtWP3 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtWP4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtWP4 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHWP1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHWP1 As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblFax control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblFax As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtFax1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFax1 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtFax2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFax2 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtFax3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFax3 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHFax1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHFax1 As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblAddress1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAddress1 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtAddress1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAddress1 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHAddress1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHAddress1 As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblAddress2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAddress2 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtAddress2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAddress2 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHAddress2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHAddress2 As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblMunicipality control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMunicipality As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtMunicipality control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtMunicipality As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHMunicipality control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHMunicipality As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblProvince control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblProvince As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlProvince control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlProvince As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHProvince control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHProvince As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblPostalCode control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblPostalCode As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtPostalCode control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtPostalCode As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHPostalCode control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHPostalCode As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblRequest control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblRequest As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''cklRequest control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cklRequest As Global.System.Web.UI.WebControls.CheckBoxList

	'''<summary>
	'''btnHRequest control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHRequest As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblUsername control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblUsername As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''uplUsername control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents uplUsername As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''txtUsername control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtUsername As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHUsername control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHUsername As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''uplSection control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents uplSection As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''grdSection control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdSection As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''lblPassword control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblPassword As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''uplPwd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents uplPwd As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''txtPassword control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHPassword control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHPassword As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnGenerate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnGenerate As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblUserGroup control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblUserGroup As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlUserGroup control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlUserGroup As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHGroup control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHGroup As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblUserLevel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblUserLevel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''uplLevel2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents uplLevel2 As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''ddlUserLevel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlUserLevel As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHUserLevel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHUserLevel As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnAddLevel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAddLevel As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''uplLevel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents uplLevel As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''lstUserLevel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lstUserLevel As Global.System.Web.UI.WebControls.ListBox

	'''<summary>
	'''btnRemoveLevel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnRemoveLevel As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblSecurity control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSecurity As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlSecurity control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlSecurity As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHSecurity control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHSecurity As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblAnswer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAnswer As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtAnswer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAnswer As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHAnswer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHAnswer As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblActive control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblActive As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''rblActive control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rblActive As Global.System.Web.UI.WebControls.RadioButtonList

	'''<summary>
	'''btnHActive control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHActive As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''Master property.
	'''</summary>
	'''<remarks>
	'''Auto-generated property.
	'''</remarks>
	Public Shadows ReadOnly Property Master() As PATMAP.MasterPage
		Get
			Return CType(MyBase.Master, PATMAP.MasterPage)
		End Get
	End Property
End Class
