'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class viewfunctions

	'''<summary>
	'''btnAdd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblFunctionName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblFunctionName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtFunctionName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFunctionName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHFunctionName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHFunctionName As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''uplFunction control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents uplFunction As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''lblTotal control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotal As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtTotal control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtTotal As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''grdFunctions control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdFunctions As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''Master property.
	'''</summary>
	'''<remarks>
	'''Auto-generated property.
	'''</remarks>
	Public Shadows ReadOnly Property Master() As PATMAP.MasterPage
		Get
			Return CType(MyBase.Master, PATMAP.MasterPage)
		End Get
	End Property
End Class
