'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class graphs

	'''<summary>
	'''subMenu control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents subMenu As Global.PATMAP.tabmenu

	'''<summary>
	'''updTables control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents updTables As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''lbStep1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbStep1 As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbStep2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbStep2 As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbStep3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbStep3 As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbStep4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbStep4 As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbStep5 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbStep5 As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbStepFinal control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbStepFinal As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lblScenarioName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblScenarioName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''uplName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents uplName As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''txtScenarioName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtScenarioName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHScenarioName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHScenarioName As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSave As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblBase control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblBase As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtBaseTaxYrModel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtBaseTaxYrModel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblSubject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSubject As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtSubjectTaxYrModel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSubjectTaxYrModel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlReport control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlReport As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHReport control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHReport As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''ddlJurisTypeGroup control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlJurisTypeGroup As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHJurisTypeGroup control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHJurisTypeGroup As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''ddlJurisType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlJurisType As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHJurisType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHJurisType As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''ddlMunicipality control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlMunicipality As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHMunicipality control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHMunicipality As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''ddlSchoolDivision control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlSchoolDivision As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHSchoolDivision control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHSchoolDivision As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnTaxStaus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnTaxStaus As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnHTaxStaus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHTaxStaus As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''ddlTaxStatus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlTaxStatus As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHTaxStatus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHTaxStatus As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnClasses control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnClasses As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnHClasses control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHClasses As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''ddlTaxClasses control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlTaxClasses As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHTaxClasses control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHTaxClasses As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''ddlTaxType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlTaxType As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHTaxType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHTaxType As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''txtParcelNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtParcelNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHParcelNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHParcelNo As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnShow control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnShow As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''Master property.
	'''</summary>
	'''<remarks>
	'''Auto-generated property.
	'''</remarks>
	Public Shadows ReadOnly Property Master() As PATMAP.MasterPage
		Get
			Return CType(MyBase.Master, PATMAP.MasterPage)
		End Get
	End Property
End Class
