'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class start

	'''<summary>
	'''subMenu control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents subMenu As Global.PATMAP.tabmenu

	'''<summary>
	'''pnlChoice control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlChoice As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''rdlScenarioType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rdlScenarioType As Global.System.Web.UI.WebControls.RadioButtonList

	'''<summary>
	'''btnHScenarioType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHScenarioType As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''pnlNew control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlNew As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblBaseModel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblBaseModel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlBaseModel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlBaseModel As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHBaseModel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHBaseModel As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblSubjectModel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSubjectModel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlSubjectModel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlSubjectModel As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHSubjectModel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHSubjectModel As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''pnlSaved control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlSaved As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblFrom control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblFrom As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblTo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblUser As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlUser As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHUser As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblDateCreated control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDateCreated As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtDateFrom control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDateFrom As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnDateFrom control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnDateFrom As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''calDateFrom control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents calDateFrom As Global.AjaxControlToolkit.CalendarExtender

	'''<summary>
	'''txtDateTo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDateTo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnDateTo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnDateTo As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''calDateTo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents calDateTo As Global.AjaxControlToolkit.CalendarExtender

	'''<summary>
	'''btnHDateCreated control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHDateCreated As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblScenarioName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblScenarioName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtScenarioName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtScenarioName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHScenarioName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHScenarioName As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblSavedBase control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSavedBase As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlSavedBase control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlSavedBase As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHSavedBase control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHSavedBase As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblSavedSubject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSavedSubject As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlSavedSubject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlSavedSubject As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHSavedSubject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHSavedSubject As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblAudience control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAudience As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlAudience control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlAudience As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHAudience control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHAudience As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnClear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnClear As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''uplScenario control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents uplScenario As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''lblTotal control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTotal As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtTotal control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtTotal As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''grdStart control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdStart As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''btnContinue control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnContinue As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''Master property.
	'''</summary>
	'''<remarks>
	'''Auto-generated property.
	'''</remarks>
	Public Shadows ReadOnly Property Master() As PATMAP.MasterPage
		Get
			Return CType(MyBase.Master, PATMAP.MasterPage)
		End Get
	End Property
End Class
