'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''editpotash class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class editpotash

    '''<summary>
    '''subMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subMenu As Global.PATMAP.tabmenu

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tr_DSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_DSN As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDSN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlDSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDSN As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnHDSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHDSN As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tr_MunicipalityType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_MunicipalityType As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblMunicipalityType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMunicipalityType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlMunicipalityType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMunicipalityType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnHMunicipalityType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHMunicipalityType As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblpotashAreaID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpotashAreaID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtpotashAreaID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpotashAreaID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnHpotashAreaID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHpotashAreaID As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''RangeValidatortxtpotashAreaID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidatortxtpotashAreaID As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''lblMunicipalityID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMunicipalityID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlMunicipalityID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMunicipalityID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnHMunicipalityID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHMunicipalityID As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tr_areaInSquareMiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_areaInSquareMiles As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblareaInSquareMiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblareaInSquareMiles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtareaInSquareMiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtareaInSquareMiles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnHareaInSquareMiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHareaInSquareMiles As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''RangeValidatorareaInSquareMiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidatorareaInSquareMiles As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''tr_statutoryDiscountPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_statutoryDiscountPercentage As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblstatutoryDiscountPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstatutoryDiscountPercentage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtstatutoryDiscountPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstatutoryDiscountPercentage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnHstatutoryDiscountPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHstatutoryDiscountPercentage As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''RangeValidatorstatutoryDiscountPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidatorstatutoryDiscountPercentage As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''tr_millRateFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_millRateFactor As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblmillRateFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmillRateFactor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmillRateFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmillRateFactor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnHmillRateFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHmillRateFactor As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''RangeValidatormillRateFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidatormillRateFactor As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''lbltotalPoints control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltotalPoints As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txttotalPoints control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttotalPoints As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnHtotalPoints control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHtotalPoints As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''RangeValidatortotalPoints control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidatortotalPoints As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''tr_boardAdjustments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_boardAdjustments As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblboardAdjustments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblboardAdjustments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtboardAdjustments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtboardAdjustments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnHboardAdjustments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHboardAdjustments As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''RangeValidatorboardAdjustments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidatorboardAdjustments As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''lbltotalGrant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltotalGrant As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txttotalGrant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttotalGrant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnHtotalGrant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHtotalGrant As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''RangeValidatortotalGrant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidatortotalGrant As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As PATMAP.MasterPage
        Get
            Return CType(MyBase.Master, PATMAP.MasterPage)
        End Get
    End Property
End Class
