'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class loadassessment

    '''<summary>
    '''subMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subMenu As Global.PATMAP.tabmenu

    '''<summary>
    '''FlashfileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlashfileUpload As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFile As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fpFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fpFile As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnHFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHFile As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnFileUpload_New control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFileUpload_New As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''FlashfileUpload_p control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlashfileUpload_p As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''LinkButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButton1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tr_ddlTableNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlTableNames As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTableNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTableNames As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlISCParcelNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlISCParcelNumber As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlISCParcelNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlISCParcelNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlISCParcelNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlISCParcelNumber As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlparcelID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlparcelID As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlparcelID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlparcelID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlparcelID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlparcelID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlmunicipalityID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlmunicipalityID As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlmunicipalityID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlmunicipalityID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlmunicipalityID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlmunicipalityID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlalternate_parcelID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlalternate_parcelID As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlalternate_parcelID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlalternate_parcelID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlalternate_parcelID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlalternate_parcelID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlLLD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlLLD As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlLLD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlLLD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlLLD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLLD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlcivicAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlcivicAddress As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlcivicAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlcivicAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlcivicAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlcivicAddress As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlpresentUseCodeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlpresentUseCodeID As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlpresentUseCodeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlpresentUseCodeID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlpresentUseCodeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlpresentUseCodeID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlschoolID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlschoolID As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlschoolID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlschoolID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlschoolID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlschoolID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddltaxClassID_orig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddltaxClassID_orig As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddltaxClassID_orig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddltaxClassID_orig As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddltaxClassID_orig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddltaxClassID_orig As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlmarketValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlmarketValue As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlmarketValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlmarketValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlmarketValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlmarketValue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddltaxable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddltaxable As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddltaxable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddltaxable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddltaxable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddltaxable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlotherExempt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlotherExempt As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlotherExempt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlotherExempt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlotherExempt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlotherExempt As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlFGIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlFGIL As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlFGIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlFGIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlFGIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFGIL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlPGIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlPGIL As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlPGIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlPGIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlPGIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPGIL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlSection293 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlSection293 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlSection293 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlSection293 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlSection293 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSection293 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlByLawExemption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlByLawExemption As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlByLawExemption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlByLawExemption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlByLawExemption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlByLawExemption As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_Aggregate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_Aggregate As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ckbAggregate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbAggregate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnHAggregate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHAggregate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tr_DataSet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_DataSet As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDataSet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataSet As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExisting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExisting As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlDSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDSN As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnHDSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHDSN As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tr_txtNewDSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_txtNewDSN As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblOr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewDSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewDSN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnHNewDSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHNewDSN As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tr_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_Year As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYear As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnHYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHYear As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tr_btnLoad_SSIS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_btnLoad_SSIS As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''btnLoad_SSIS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLoad_SSIS As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tr_btnLoad_SQL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_btnLoad_SQL As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''btnLoad_SQL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLoad_SQL As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''rpvReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpvReports As Global.Microsoft.Reporting.WebForms.ReportViewer

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As PATMAP.MasterPage
        Get
            Return CType(MyBase.Master, PATMAP.MasterPage)
        End Get
    End Property
End Class
