'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.312
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''loadmunicipal class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class loadmunicipal

    '''<summary>
    '''subMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subMenu As Global.PATMAP.tabmenu

    '''<summary>
    '''lblFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFile As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fpFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fpFile As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnHFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHFile As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnFileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFileUpload As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblFile1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFile1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fpFileMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fpFileMap As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnHMapFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHMapFile As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnFileUploadMAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFileUploadMAP As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tr_ddlTableMunicipalitiesMapLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlTableMunicipalitiesMapLink As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlTableMunicipalitiesMapLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlTableMunicipalitiesMapLink As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTableMunicipalitiesMapLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTableMunicipalitiesMapLink As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlTableJurisdGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlTableJurisdGroups As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlTableJurisdGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlTableJurisdGroups As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTableJurisdGroups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTableJurisdGroups As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlTableJurisdTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlTableJurisdTypes As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlTableJurisdTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlTableJurisdTypes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTableJurisdTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTableJurisdTypes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlTableEntities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlTableEntities As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlTableEntities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlTableEntities As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTableEntities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTableEntities As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_ddlTableMunicRollup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_ddlTableMunicRollup As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lb_ddlTableMunicRollup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_ddlTableMunicRollup As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTableMunicRollup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTableMunicRollup As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tr_btnLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_btnLoad As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''btnLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLoad As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tr_btnLoadMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_btnLoadMap As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''btnLoadMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLoadMap As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''rpvReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpvReports As Global.Microsoft.Reporting.WebForms.ReportViewer

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As PATMAP.MasterPage
        Get
            Return CType(MyBase.Master, PATMAP.MasterPage)
        End Get
    End Property
End Class
