'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5472
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class loadpotash

	'''<summary>
	'''subMenu control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents subMenu As Global.PATMAP.tabmenu

	'''<summary>
	'''lblFile control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblFile As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''fpFile control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents fpFile As Global.System.Web.UI.WebControls.FileUpload

	'''<summary>
	'''btnHFile control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHFile As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnFileUpload control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnFileUpload As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''tr_ddlTableAreas control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tr_ddlTableAreas As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''Label1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlTableAreas control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlTableAreas As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''tr_ddlTableParcels control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tr_ddlTableParcels As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''Label2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlTableParcels control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlTableParcels As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''tr_ddlTableRural control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tr_ddlTableRural As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''Label3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlTableRural control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlTableRural As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''tr_ddlTableUrban control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tr_ddlTableUrban As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''Label4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlTableUrban control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlTableUrban As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''tr_DataSet control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tr_DataSet As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''lblDataSet control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDataSet As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblExisting control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblExisting As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlDSN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlDSN As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHDSN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHDSN As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''tr_txtNewDSN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tr_txtNewDSN As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''lblOr control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblOr As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtNewDSN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtNewDSN As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHNewDSN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHNewDSN As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''tr_Year control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tr_Year As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''lblYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblYear As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlYear As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHYear As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''tr_btnLoad control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tr_btnLoad As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''btnLoad control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnLoad As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''rpvReports control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rpvReports As Global.Microsoft.Reporting.WebForms.ReportViewer

	'''<summary>
	'''Master property.
	'''</summary>
	'''<remarks>
	'''Auto-generated property.
	'''</remarks>
	Public Shadows ReadOnly Property Master() As PATMAP.MasterPage
		Get
			Return CType(MyBase.Master, PATMAP.MasterPage)
		End Get
	End Property
End Class
