'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class main

	'''<summary>
	'''subMenu control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents subMenu As Global.PATMAP.tabmenu

	'''<summary>
	'''lblTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblSubjMun control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSubjMun As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlSubjMun control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlSubjMun As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHSubjMun control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHSubjMun As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblOriginMun control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblOriginMun As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlOriginMun control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlOriginMun As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHOriginMun control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHOriginMun As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblDestinationMun control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDestinationMun As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlDestinationMun control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlDestinationMun As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnHDestinationMun control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHDestinationMun As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblGroupName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblGroupName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtGroupName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtGroupName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnHGroupName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHGroupName As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''pnlRestructuredLevy control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlRestructuredLevy As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblRestructuredLevy control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblRestructuredLevy As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''rblRestructuredLevy control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rblRestructuredLevy As Global.System.Web.UI.WebControls.RadioButtonList

	'''<summary>
	'''btnHRestructuredLevy control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHRestructuredLevy As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblTransfer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTransfer As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblParcelNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblParcelNo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtParcelNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtParcelNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''chkSelectAll control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkSelectAll As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''btnHParcelNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHParcelNo As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnLinearAdj control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnLinearAdj As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnHLinearAdj control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHLinearAdj As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnUseMap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnUseMap As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnHUseMap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHUseMap As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnTransfer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnTransfer As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''grdProperties control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdProperties As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''btnSubmit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''grdAssessment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdAssessment As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''btnPrintDpl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnPrintDpl As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''grdDuplicateProp control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdDuplicateProp As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''Master property.
	'''</summary>
	'''<remarks>
	'''Auto-generated property.
	'''</remarks>
	Public Shadows ReadOnly Property Master() As PATMAP.MasterPage
		Get
			Return CType(MyBase.Master, PATMAP.MasterPage)
		End Get
	End Property
End Class
