'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.312
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''mintax class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class mintax

    '''<summary>
    '''subMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents subMenu As Global.PATMAP.tabmenu

    '''<summary>
    '''lblSubjYr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubjYr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLiveSubjYr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLiveSubjYr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubjMun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubjMun As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLiveSubjMun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLiveSubjMun As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStartingUniformMillRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStartingUniformMillRate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLiveStartingUniformMillRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLiveStartingUniformMillRate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStartingRevenue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStartingRevenue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLiveStartingRevenue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLiveStartingRevenue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''uplMinTax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplMinTax As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grdMinTax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdMinTax As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReset As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblRevisedUniformMillRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRevisedUniformMillRate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRevisedUniformMillRateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRevisedUniformMillRateValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRevisedModelRevenue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRevisedModelRevenue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRevisedModelRevenueValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRevisedModelRevenueValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As PATMAP.MasterPage
        Get
            Return CType(MyBase.Master, PATMAP.MasterPage)
        End Get
    End Property
End Class
