'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.312
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''logout class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class logout

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As PATMAP.NoLogin
        Get
            Return CType(MyBase.Master, PATMAP.NoLogin)
        End Get
    End Property
End Class
